In [1]:
import torch
import math

In [2]:
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

# For this example, the output y is a linear function of (x, x^2, x^3), so
# we can consider it as a linear layer neural network. Let's prepare the
# tensor (x, x^2, x^3).

In [3]:
p = torch.tensor([1, 2, 3])
xx = x.unsqueeze(-1).pow(p)

In [4]:
xx

tensor([[ -3.1416,   9.8696, -31.0063],
        [ -3.1384,   9.8499, -30.9133],
        [ -3.1353,   9.8301, -30.8205],
        ...,
        [  3.1353,   9.8301,  30.8205],
        [  3.1384,   9.8499,  30.9133],
        [  3.1416,   9.8696,  31.0063]])

In [5]:
x.unsqueeze(-1).shape

torch.Size([2000, 1])

In [6]:
x = torch.randn(78,1) / math.sqrt(784)
y = torch.randn(784,2) / math.sqrt(784)

In [7]:
y.T.shape

torch.Size([2, 784])

In [8]:
a = torch.randn(4, 4)
a

tensor([[-0.0848, -1.3882, -0.0451,  0.5075],
        [-0.1046, -0.0691, -0.1119, -0.9572],
        [ 0.0634,  1.5166,  0.6102,  0.8758],
        [ 0.9901,  0.5253, -1.4441, -0.4655]])

In [9]:
torch.argmax(a, dim = -2)

tensor([3, 2, 2, 2])

In [6]:
lst = [[1,2],[2,3],[3,4]]

In [10]:
x = lst[:, None]
x

TypeError: list indices must be integers or slices, not tuple