In [1]:
import torch
import numpy as np

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [2]:
x = torch.zeros([2,5])

In [3]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [6]:
y = torch.rand([2,5])

In [7]:
y

tensor([[0.2292, 0.1382, 0.6861, 0.2868, 0.9126],
        [0.5878, 0.1852, 0.7030, 0.6123, 0.5048]])

In [10]:
y.view([1,10])

tensor([[0.2292, 0.1382, 0.6861, 0.2868, 0.9126, 0.5878, 0.1852, 0.7030, 0.6123,
         0.5048]])